spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1 # Substitua <HOST>, <PORT> e <SID> pelos valores reais
    driverClassName: oracle.jdbc.OracleDriver
    schema: MPUSER
    #username: system
    username: MPUSER
    password: 123456
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml  # Verifique o caminho do arquivo de changelog
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    default-schema: MPUSER
    #user: system
    user: MPUSER
    password: 123456

  sql:
    init:
      mode: never  # Isso impede que o Spring tente criar um banco em memória


