spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB # Substitua <HOST>, <PORT> e <SID> pelos valores reais
    driverClassName: oracle.jdbc.OracleDriver
    username: C##MPUSER
    password: 123456
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB
    user: C##MPUSER
    password: 123456

  profiles:
    active: test
